name: google-chat # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Unofficial Google Chat application.
description: |
  The unofficial Google Chat application.
  Chat makes it easy for teams to be able to get their work done in one place. 
  From direct messages to group conversations, Chat helps teams collaborate easily and efficiently. 
  With dedicated, virtual rooms to house projects over time — plus threaded conversations — 
  Chat makes it simple to track progress and follow up tasks. 
  Chat currently supports 28 languages and each room can support up to 8,000 members.

grade: stable
confinement: strict

parts:
  electron-app:
    source: .
    plugin: nodejs
    

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio


    after:
      - desktop-gtk2


    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL
    prime:
      - -node_modules

apps:
  google-chat:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/google-chat
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl